.Phony : all Test

All : P1 P2 P3 P4

P1 : Problem1.c
	gcc -pthread csapp.c Problem1.c -o P1

P2 : Problem2.c	
	gcc -pthread csapp.c Problem2.c -o P2

P3 : Problem3.c
	gcc -pthread csapp.c Problem3.c -o P3

P4 : Problem4.c
	gcc -pthread csapp.c Problem4.c -o P4
