#!/bin/bash
find=$1
replace=$2
prefix=$3

# Run Bash and C version of the same program
# Compares resulting files
# If resulting files are identical, then nothing is
# outputted
# If resulting files are different, "Failed Test" is printed





# --------------------------------------------------------------------
# Bash version of H3 Program
# Store processed files in folder called testing

rm -rf testing/
mkdir testing/

declare -a found # 1 = found, 0 = not found
declare -a filenames # filenames, associated array with found
file_num=0 # total number of files processed

# Replace
# Use sed to replace `find` with `replace`
for filename in ./*.txt; do
	sed 's/'"$find"'/'"$replace"'/g' "$filename" > "testing/$filename"

	filenames[file_num]=$filename

	DIFF=$(diff "$filename" "testing/$filename") 
	if [ "$DIFF" != "" ]; then
  		found[file_num]=1 # found
	else
		found[file_num]=0 # not found
	fi

	file_num=$((file_num + 1))
done

file_num=$((file_num - 1))

# Prepend, if not replaced
# Use sed to replace `prefix` with `find``prefix`
for file_counter in `seq 0 "$file_num"`; do
	if [ "${found[$file_counter]}" = 0 ]; then
		sed 's/'"$prefix"'/'"$find""$prefix"'/g' "${filenames[$file_counter]}"  > "testing/${filenames[$file_counter]}"
	fi
done
# --------------------------------------------------------------------





# --------------------------------------------------------------------
# Run C version
./H3 "$find" "$replace" "$prefix" > H3-output
# --------------------------------------------------------------------




# --------------------------------------------------------------------
# Compare bash-H3 with C version of H3
for filename in ./*.txt; do

	DIFF=$(diff "$filename" "testing/$filename") 
	if [ "$DIFF" != "" ]; then
  		echo "Failed Test: "$filename
	fi

done
# --------------------------------------------------------------------