#!/bin/bash
find=$1
replace=$2
prefix=$3

# Run Bash and C version of the same program
# Compares resulting files
# If resulting files are identical, then nothing is
# outputted
# If resulting files are different, "Failed Test" is printed

# Run Bash version
# Processed files stored in folder called testing
./bash-H3 "$find" "$replace" "$prefix"

# Run C version
./H3 "$find" "$replace" "$prefix" > H3-output

# Compare bash-H3 with C version of H3
for filename in ./*.txt; do

	DIFF=$(diff "$filename" "testing/$filename") 
	if [ "$DIFF" != "" ]; then
  		echo "Failed Test: "$filename
	fi

done
