#!/bin/bash
find=$1
replace=$2
prefix=$3

# Run bash version
bash-H3 "$find" "$replace" "$prefix"

# Run C version
./H3 "$find" "$replace" "$prefix"

# Compare bash-H3 with C version of H3
for filename in ./*.txt; do

	DIFF=$(diff "$filename" "testing/$filename") 
	if [ "$DIFF" != "" ]; then
  		echo "Failed Test: "$filename
	fi
done