.Phony : all Test

All : Problem1.o Problem2.o Problem3.o special.o

Problem1.o : Problem1.c
	gcc Problem1.c -o Problem1.o

Problem2.o : Problem2.c	
	gcc Problem2.c -o Problem2.o

Problem3.o : Problem3.c
	gcc Problem3.c -o Problem3.o

special.o : special.c
	gcc special.c -o special.o
